### ISSUE TITLE
2.0.5 fails to start Jack on Fedora

### ISSUE THREAD

**Issue by eeickmeyer** [ovenwerks/studio-controls#1]
This occurs when attempting to start Jack:

```
2020-08-11 21:43:19,894 - root - INFO - Running: config_start()
2020-08-11 21:43:19,896 - root - DEBUG - log level: 9
2020-08-11 21:43:21,913 - root - DEBUG - Kill old Procs: 
2020-08-11 21:43:21,922 - root - DEBUG - remove jackdbus_detect: Connection failure: Connection refused
pa_context_connect() failed: Connection refused
2020-08-11 21:43:21,931 - root - DEBUG - remove module-udev-detect: Connection failure: Connection refused
pa_context_connect() failed: Connection refused
2020-08-11 21:43:21,939 - root - DEBUG - remove module-alsa-card: Connection failure: Connection refused
pa_context_connect() failed: Connection refused
2020-08-11 21:43:21,940 - root - INFO - HDMI device, setting buffer to 4096
2020-08-11 21:43:21,970 - root - DEBUG - Found previous jack config removing
2020-08-11 21:43:22,518 - root - DEBUG - Jackdbus: --- driver select "alsa"
2020-08-11 21:43:22,597 - root - DEBUG - Jackdbus: --- driver param set "device" -> "hw:NVidia,3,0"
--- driver param set "rate" -> "48000"
2020-08-11 21:43:23,200 - root - DEBUG - Jackdbus: --- driver param set "period" -> "4096"
--- driver param set "nperiods" -> "3"
--- start
2020-08-11 21:43:25,321 - root - DEBUG - jack client created
2020-08-11 21:43:25,331 - root - DEBUG - Pulseaudio: Connection failure: Connection refused
pa_context_connect() failed: Connection refused
2020-08-11 21:43:25,340 - root - DEBUG - Pulseaudio: Connection failure: Connection refused
pa_context_connect() failed: Connection refused
2020-08-11 21:43:27,344 - root - DEBUG - jack connect system:capture_1 from pulse_in:front-left
2020-08-11 21:43:27,344 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/autojack", line 1102, in ses_cb_start
    config_start()
  File "/usr/bin/autojack", line 566, in config_start
    connect_pa()
  File "/usr/bin/autojack", line 747, in connect_pa
    jack_client.connect(p_in_con[i], f"{name}:front-left")
  File "/usr/lib/python3.9/site-packages/jack.py", line 498, in connect
    _check(err,
  File "/usr/lib/python3.9/site-packages/jack.py", line 3025, in _check
    raise JackErrorCode(msg, error_code)
jack.JackErrorCode: Error connecting 'system:capture_1' -> 'pulse_in:front-left' (-1)
2020-08-11 21:43:27,390 - root - DEBUG - Connection changed
2020-08-11 21:43:27,390 - root - DEBUG - moving connections from system:playback_1 to system:playback_1
2020-08-11 21:43:27,390 - root - DEBUG - both ports are the same, no move done

```

**Comment by ghost** [comment]
I'm on Ubuntu 20.04 and when Ubuntu Studio Controls became Studio Controls, i could no longer start Jack and had to remove the  backports ppa and go back to Ubuntu Studio Controls

**Comment by eeickmeyer** [comment]
> I'm on Ubuntu 20.04 and when Ubuntu Studio Controls became Studio Controls, i could no longer start Jack and had to remove the backports ppa and go back to Ubuntu Studio Controls

That is a separate issue then. If you're having difficulty with that, please file a new issue. On my Ubuntu system, I cannot reproduce, so there's likely a configuration issue on your end. This issue has to do with Fedora, so your issue is separate and is a support issue rather than a bug.

**Comment by ghost** [comment]
Hi Eeikmeyer. Yes, this was not the place to report the bug. Sorry about that.
For other reasons, I reinstalled ubuntu the other days, and added the backports repository, and Studio Controls 2.0 works totally fine, so there's nothing to see here. If it happens again I will make a proper bug report.

**Comment by eeickmeyer** [comment]
Looks like this may have been a packaging/compilation bug, so I'm just waiting to be able to test it further on Fedora.

**Comment by eeickmeyer** [comment]
This ended up being a bug in LTO optimization in Fedora, so closing.
