### ISSUE TITLE
Out of range error on "Remove output bridge"

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#29]
I clicked the remove Pulse bridge button and got this console output (spaces added);

```
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1110, in pj_out_rem_cb
    self.refresh_pulse_tab(self.i_in, self.i_out)
  File "/usr/bin/studio-controls", line 992, in refresh_pulse_tab
    self.pj_out_count.set_value(int(self.p_out_cnt[i_out]))
IndexError: list index out of range

Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1105, in pj_out_rem_cb
    del self.p_out_cnt[index]
IndexError: list assignment index out of range

Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1103, in pj_out_rem_cb
    del self.pulse_out[index]
IndexError: list assignment index out of range

Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1103, in pj_out_rem_cb
    del self.pulse_out[index]
IndexError: list assignment index out of range
```

**Comment by mxmilkiib** [comment]
I realise now the device dropdown menu is not populated;

![image](https://user-images.githubusercontent.com/108225/100312648-c91d0480-2faa-11eb-8a28-5c6d39c5f886.png)

**Comment by ovenwerks** [comment]
The whole design of the how parameters are stored has been changed and now no longer uses offsets. SO this problem in particular is fixed. We have tried to catch calls to non-existing and hopefully have gotten them all.
