### ISSUE TITLE
Error converting new config format

### ISSUE THREAD

**Issue by Marzal** [ovenwerks/studio-controls#31]
studio-controls

```bash
Config file: /home/dmc/.config/autojack/autojack.json
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1429, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 420, in __init__
    with open(c_file) as f:
FileNotFoundError: [Errno 2] No existe el fichero o el directorio: '/home/dmc/.config/autojack/autojack.json'
```
/usr/bin/convert-studio-controls
```bash
read_old
make_db
write_new
Traceback (most recent call last):
  File "/usr/bin/convert-studio-controls", line 285, in <module>
    main()
  File "/usr/bin/convert-studio-controls", line 281, in main
    write_new()
  File "/usr/bin/convert-studio-controls", line 269, in write_new
    c_dir = expanduser(self.config_path)
NameError: name 'self' is not defined
```
I think the problem is here
https://github.com/ovenwerks/studio-controls/blob/e59d96215f142137d3bbf72ab3bf27b2f76feb4d/usr/bin/convert-studio-controls#L269

Removing "**self**" makes de conversion works

**Comment by eeickmeyer** [comment]
Haven't tried the fix yet, but I encountered this as well. I recommend merging the PR.
