### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by eeickmeyer** [ovenwerks/studio-controls#33]
Getting this after converting and before starting:

```
Config file: /home/erich/.config/autojack/autojack.json
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1429, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 424, in __init__
    self.devdb.scan_dev(self.conf_db)
  File "/usr/bin/studio-controls", line 150, in scan_dev
    self.get_dev_info(conf['devices'][cname], conf['jack'])
  File "/usr/bin/studio-controls", line 166, in get_dev_info
    with open(f"/proc/asound/card{str(x)}/stream0", "r") as card_file:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/asound/card3/stream0'
```

**Comment by ovenwerks** [comment]
This issue has been resolved with 2.0.23-pre
