### ISSUE TITLE
Fail to start with autojack.json missing

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#36]
```
Config file: /home/milk/.config/autojack/autojack.json
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1445, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 428, in __init__
    with open(c_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/milk/.config/autojack/autojack.json'
```

Don't know what I did, but I have;
```
5:05:11 milk@rose:~ % ll .config/autojack 
total 12K
4.0K -rw-r--r-- 1 milk milk   4 Dec  2 18:11 autojack.lock
4.0K -rw-r--r-- 1 milk milk 624 Dec  2 19:33 autojackrc
4.0K -rw-r--r-- 1 milk milk   6 Dec 11 05:03 studio-controls.lock
```

**Comment by eeickmeyer** [comment]
Try running convert-studio-controls from the command line and post its output. We're moving to a json config file.

**Comment by mxmilkiib** [comment]
I had tried just removing the directory but I got the same error. Now it just has studio-controls.lock, but I still get the same message when trying `studio-controls`

`convert-studio-controls` gives this;

```
read old file
make new data base
Traceback (most recent call last):
  File "/usr/bin/convert-studio-controls", line 289, in <module>
    main()
  File "/usr/bin/convert-studio-controls", line 284, in main
    make_db()
  File "/usr/bin/convert-studio-controls", line 160, in make_db
    our_db = {'version': version}
NameError: name 'version' is not defined
```

**Comment by ovenwerks** [comment]
Thank you, that is a spelling mistake. Fixed in next version.
