### ISSUE TITLE
Cannot run studio-controls on Ubuntu 20.10

### ISSUE THREAD

**Issue by benjaminbellamy** [ovenwerks/studio-controls#43]
I installed ubuntustudio-installer on top of a regular Ubuntu 20.10.
Whenever I run studio-controls (`2.1.0-0ubuntu1~ubuntu20.10.1~ppa1`) I get this error:
```Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1420, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 426, in __init__
    jack.set_error_function(callback=self.jack_error)
  File "/usr/lib/python3/dist-packages/jack.py", line 2835, in set_error_function
    _set_error_or_info_function(callback, _lib.jack_set_error_function)
  File "/usr/lib/python3/dist-packages/jack.py", line 2874, in _set_error_or_info_function
    def callback_wrapper(msg):
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
```

**Comment by ovenwerks** [comment]
This is not a bug with Studio Controls but with libffi I am pretty sure a fix is being worked on, but nothing I can do from here.
