### ISSUE TITLE
PipeWire issues (on Arch)

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#48]
I'm using the Arch Linux PipeWire [Pulseaudio dropin](https://archlinux.org/packages/extra/x86_64/pipewire-pulse/) package which doesn't require the PA binary.

```
Feb 10 15:03:03 rose.local autojack[2660]: Traceback (most recent call last):
Feb 10 15:03:03 rose.local autojack[2660]:   File "/usr/lib/python3.9/site-packages/gi/_ossighelper.py", line 92, in signal_notify
Feb 10 15:03:03 rose.local autojack[2660]:     def signal_notify(source, condition):
Feb 10 15:03:03 rose.local autojack[2660]:   File "/usr/bin/autojack", line 1056, in handler
Feb 10 15:03:03 rose.local autojack[2660]:     we_die()
Feb 10 15:03:03 rose.local autojack[2660]:   File "/usr/bin/autojack", line 1074, in we_die
Feb 10 15:03:03 rose.local autojack[2660]:     cp = subprocess.run(["/usr/bin/pulseaudio", "-k"],
Feb 10 15:03:03 rose.local autojack[2660]:   File "/usr/lib/python3.9/subprocess.py", line 501, in run
Feb 10 15:03:03 rose.local autojack[2660]:     with Popen(*popenargs, **kwargs) as process:
Feb 10 15:03:03 rose.local autojack[2660]:   File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
Feb 10 15:03:03 rose.local autojack[2660]:     self._execute_child(args, executable, preexec_fn, close_fds,
Feb 10 15:03:03 rose.local autojack[2660]:   File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
Feb 10 15:03:03 rose.local autojack[2660]:     raise child_exception_type(errno_num, err_msg, err_filename)
Feb 10 15:03:03 rose.local autojack[2660]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pulseaudio'
```

**Comment by ovenwerks** [comment]
studio-controls is not pw ready by any means. And to be honest pipewire is not ready for full time use either. And on top of that, pipewire already does most of what studio-controls does internally. Controls will support pipewire when it is ready for everyday use and more common. perhaps around the next ubuntu LTS, but perhaps sooner as pw moves into the debian/ubuntu world.
