### ISSUE TITLE
Recent Ubuntu 21.04 updates to pulseaudio seem prevent studio-controls from starting JACK

### ISSUE THREAD

**Issue by kaerumy** [ovenwerks/studio-controls#60]
The problem seems to be Ubuntu pulseaudio related, but I'm not sure how to get more debugging info. Able to get JACK started by killing pulseaudio and using QJacktl instead. But can't start it on launch or manually clicking start button in studio-control, same message.. jack server not running or cannot be started.

pulseaudio                                 1:14.2-1ubuntu1.1 
pulseaudio-module-jack             1:14.2-1ubuntu1.1
studio-controls                            2.1.4-0ubuntu1

Starting Autojack...
jack message received: jack server is not running or cannot be started

```
{
    "version": "2.1.4",
    "log-level": 15,
    "jack": {
        "on": true,
        "driver": "alsa",
        "chan-in": 1,
        "chan-out": 1,
        "rate": 48000,
        "frame": 128,
        "period": 2,
        "connect-mode": "n",
        "dev": "0,0,0",
        "usbdev": "M4,0,0"
    },
    "extra": {
        "a2j": false,
        "usbauto": false,
        "usb-single": false,
        "monitor": "system:playback_1",
        "phone-action": "switch",
        "phone-device": "0,0,0"
    },
    "pulse": {
        "inputs": {
            "pulse_in": {
                "connection": "system:capture_1",
                "count": 2
            }
        },
        "outputs": {
            "pulse_out-1": {
                "connection": "monitor",
                "count": 2
            }
        }
    },
    "devices": {
        "0": {
            "number": -1,
            "usb": false,
            "internal": true,
            "hdmi": false,
            "rates": [
                "32000",
                "44100",
                "48000",
                "88200",
                "96000",
                "192000"
            ],
            "sub": {
                "0": {
                    "playback": true,
                    "capture": true,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                }
            }
        },
        "HDMI": {
            "number": 0,
            "usb": false,
            "internal": true,
            "hdmi": false,
            "rates": [],
            "sub": {
                "3": {
                    "playback": true,
                    "capture": false,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                },
                "7": {
                    "playback": true,
                    "capture": false,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                },
                "8": {
                    "playback": true,
                    "capture": false,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                },
                "9": {
                    "playback": true,
                    "capture": false,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                },
                "10": {
                    "playback": true,
                    "capture": false,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                }
            }
        },
        "C525": {
            "number": 1,
            "usb": true,
            "internal": false,
            "hdmi": false,
            "rates": [
                "16000",
                "24000",
                "32000",
                "48000"
            ],
            "sub": {
                "0": {
                    "playback": false,
                    "capture": true,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                }
            }
        },
        "M4": {
            "number": 2,
            "usb": true,
            "internal": false,
            "hdmi": false,
            "rates": [
                "44100",
                "48000",
                "88200",
                "96000",
                "176400",
                "192000"
            ],
            "sub": {
                "0": {
                    "playback": true,
                    "capture": true,
                    "play-chan": 0,
                    "cap-chan": 0,
                    "rate": 48000,
                    "frame": 1024,
                    "nperiods": 2,
                    "hide": false
                }
            }
        }
    }
}
```

**Comment by ovenwerks** [comment]
Huh, the only "internal" device is hdmi. Bug number one but it shouldn't effect things as you have USB devices. You might try setting log level to extra in studio-controls and start studio-controls from a terminal to see any text output and also attach ~/.log/autojack.log for me to look at. Hopefully I can release 2.2 soon which may help too.

**Comment by kaerumy** [comment]
Now jack is able to start again from studio-controls / autojack and I have not made a single change to anything, not even the USB port my audio interface is plugged in to.

Start or Restart JACK works, but the autostart after change in "Apply Audio Settings" fails. JACK will stop, but I will have to click Start or Restart JACK.

Maybe 2.2 will fix this heisenbug. Will close it, as it's working for now, maybe the traceback in the logs provides a clue.

```
2021-06-23 00:00:14,006 - root - INFO - Got config signal.
2021-06-23 00:00:14,006 - root - DEBUG - reconfigure autojack
2021-06-23 00:00:14,008 - root - DEBUG - change requires restart
2021-06-23 00:00:14,008 - root - INFO - Running: config_start()
2021-06-23 00:00:16,015 - root - DEBUG - Kill old Procs:
2021-06-23 00:00:16,015 - root - DEBUG - JACK is True start up jack
2021-06-23 00:00:16,018 - root - DEBUG - remove jackdbus_detect: Failed to unload module: Module module-jackdbus-detect not loaded
2021-06-23 00:00:16,020 - root - DEBUG - remove module-udev-detect: Failed to unload module: Module module-udev-detect not loaded
2021-06-23 00:00:16,021 - root - DEBUG - jack died callback
2021-06-23 00:00:16,028 - root - DEBUG - remove module-alsa-card: Failed to unload module: Module module-alsa-card not loaded
2021-06-23 00:00:16,028 - root - DEBUG - Found previous jack config removing
2021-06-23 00:00:16,032 - dbus.proxies - ERROR - Introspect error on :1.162:/org/jackaudio/Controller: dbus.exceptions.DBusException: org.fr
2021-06-23 00:00:16,032 - dbus.proxies - DEBUG - Executing introspect queue due to error
2021-06-23 00:00:16,033 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/autojack", line 1108, in ses_cb_config
    reconfig()
  File "/usr/bin/autojack", line 285, in reconfig
    config_start()
  File "/usr/bin/autojack", line 446, in config_start
    configure_iface.SetParameterValue(['engine', 'driver'], conf_db['jack']['driver'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.162 was not provided by any .service files
2021-06-23 00:00:16,033 - root - WARNING - Jack Message: Server is not running
2021-06-23 00:00:16,033 - root - WARNING - Jack Message: Server is not running
2021-06-23 00:00:16,037 - root - DEBUG - jack client closed and cleaned up
2021-06-23 00:01:04,190 - root - INFO - Got start signal.
2021-06-23 00:01:04,190 - root - INFO - Running: config_start()
2021-06-23 00:01:06,197 - root - DEBUG - Kill old Procs:
2021-06-23 00:01:06,198 - root - DEBUG - JACK is True start up jack
2021-06-23 00:01:06,201 - root - DEBUG - remove jackdbus_detect: Failed to unload module: Module module-jackdbus-detect not loaded
2021-06-23 00:01:06,203 - root - DEBUG - remove module-udev-detect: Failed to unload module: Module module-udev-detect not loaded
2021-06-23 00:01:06,205 - root - DEBUG - remove module-alsa-card: Failed to unload module: Module module-alsa-card not loaded
2021-06-23 00:01:10,934 - root - DEBUG - create jack client
2021-06-23 00:01:10,948 - root - DEBUG - jack client created
2021-06-23 00:01:10,967 - root - DEBUG - Pulseaudio: 36
2021-06-23 00:01:10,992 - root - DEBUG - Pulseaudio: 37
2021-06-23 00:01:10,992 - root - DEBUG - updating extra devices
2021-06-23 00:01:10,992 - root - DEBUG - updating extra devices complete
2021-06-23 00:01:12,994 - root - DEBUG - connect pulse bridges
2021-06-23 00:01:12,994 - root - DEBUG - jack connect system:capture_1 to pulse_in-1:front-left
2021-06-23 00:01:12,996 - root - DEBUG - Real left port name: system:capture_1
2021-06-23 00:01:12,996 - root - DEBUG - jack connect system:capture_2 to pulse_in-1:front-right
2021-06-23 00:01:12,996 - root - DEBUG - Real left port name: system:capture_2
2021-06-23 00:01:12,996 - root - DEBUG - jack connect pulse_out-1:front-left to system:playback_1
2021-06-23 00:01:12,996 - root - DEBUG - Real left port name: system:playback_1
2021-06-23 00:01:12,997 - root - DEBUG - jack connect pulse_out-1:front-right to system:playback_2
2021-06-23 00:01:12,997 - root - DEBUG - Real left port name: system:playback_2
2021-06-23 00:01:12,997 - root - DEBUG - Connection changed
2021-06-23 00:01:12,997 - root - DEBUG - moving connections from system:playback_1 to system:playback_1
2021-06-23 00:01:12,997 - root - DEBUG - both ports are the same, no move done
```
