### ISSUE TITLE
Crash when qmidinet and zita-njbridge are not installed

### ISSUE THREAD

**Issue by g3r** [ovenwerks/studio-controls#76]
Program crashes when qmidinet and/or zita-njbridge are not installed.
missing qmidinet:
```
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1881, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 623, in __init__
    self.refresh_net(self.znetbridge)
  File "/usr/bin/studio-controls", line 1473, in refresh_net
    if not (os.path.isfile(qmn) and os.access(qmn, os.X_OK)):
  File "/usr/lib/python3.10/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
missing zita-njbridge
```
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1881, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 623, in __init__
    self.refresh_net(self.znetbridge)
  File "/usr/bin/studio-controls", line 1494, in refresh_net
    if not (os.path.isfile(znj) and os.access(znj, os.X_OK)):
  File "/usr/lib/python3.10/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
os: Manjaro
python version: 3.10.2

**Comment by ovenwerks** [comment]
Thank you for testing... seems I used which in the wrong way. should be fix next release.
