### ISSUE TITLE
Ubuntu Controls does not start Jack

### ISSUE THREAD

**Issue by tarrasque73** [ovenwerks/studio-controls#78]
On Ubuntu Studio 21.10

Clicking on "Start or restart JACK" does not seem to be able to start Jack server.

Sometimes nothing happens, sometimes under"Jack Status" it keeps showing "Adding Bridges".

If i start Jack using QJackCtl everything seems to work fine.

**Comment by ovenwerks** [comment]
A studio-controls version would be more useful than a ubuntustudio version. Please make sure you have, ubuntustudio-installer, turned the backports on. as this looks like a know bug that has already been fixed since then in version 2.3.0 and should be available in backports.

**Comment by benjaminbanana** [comment]
hi
I've got a presonus audiobox usb96 sound card
It was working fine with UbuntuStudio 20.04 (without backport or PPa)
I recently install XUbuntu22.04 and UbuntuStudioInstaller sound packages (I don't like KDE) and the PPA

Sudio controls (v2.3.1) can't manage the sound card :
if I plug it before runing jack , jackstatus don't go further than "adding briges",nothing appears in carla's patchbay and there is an error in autojack.log :
{CODE()}2022-05-15 16:43:47,183 - AutoJack - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/autojack", line 1668, in ses_cb_command
    config_start()
  File "/usr/bin/autojack", line 826, in config_start
    extra_devices()
  File "/usr/bin/autojack", line 318, in extra_devices
    start_slave(fullname)
  File "/usr/bin/autojack", line 1362, in start_slave
    dsr = get_card_rate(ldev)
  File "/usr/bin/autojack", line 1313, in get_card_rate
    adev_h.setrate(int(try_rate))
alsaaudio.ALSAAudioError: PCM device is closed{CODE}

If I hotplug it when jack is already running :
the card  appears in carla as a midi device but nothing with sound and in autojack.log a little bit different error :
{CODE()}2022-05-15 17:10:48,139 - AutoJack - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/autojack", line 1224, in msg_cb_new
    start_slave(subname)
  File "/usr/bin/autojack", line 1362, in start_slave
    dsr = get_card_rate(ldev)
  File "/usr/bin/autojack", line 1313, in get_card_rate
    adev_h.setrate(int(try_rate))
alsaaudio.ALSAAudioError: PCM device is closed{CODE}

when I try "jack master settings" to choose the card as USB master  : no sound, excepted motorboating

the card works fine with QJackCtl. (even after i had errors with studio controls)

I've tried UbStudio 21.10, 22.04 (live sessions and installed versions), same problem
I've reinstall Ubstu 20.04 in dualboot : it works !

I ve tried others sound cards :
2 [CODEC          ]: USB-Audio - USB AUDIO  CODEC
                      BurrBrown from Texas Instruments USB AUDIO  CODEC at usb-0000:00:14.0-3, full s
3 [DUOCAPTURE     ]: USB-Audio - DUO-CAPTURE
                      Roland DUO-CAPTURE at usb-0000:00:14.0-1, full speed
I can run jack with them.

It sems like issue#78 but I have v 2.3.1
