### ISSUE TITLE
studio control does not manage usb device on ubuntu 21.10/22.04

### ISSUE THREAD

**Issue by benjaminbanana** [ovenwerks/studio-controls#81]
(first posted as a comment in  issue#78 a few days ago)
hi
I've got a presonus audiobox usb96 sound card (a common class compliant card)
It was working fine with UbuntuStudio 20.04 (without backport or PPa)
I recently install XUbuntu22.04 and UbuntuStudioInstaller sound packages (I don't like KDE) and the PPA

Sudio controls (v2.3.1) can't manage the sound card :
if I plug it before runing jack , jackstatus don't go further than "adding briges",nothing appears in carla's patchbay and there is an error in autojack.log :

```
022-05-15 16:43:47,183 - AutoJack - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/autojack", line 1668, in ses_cb_command
    config_start()
  File "/usr/bin/autojack", line 826, in config_start
    extra_devices()
  File "/usr/bin/autojack", line 318, in extra_devices
    start_slave(fullname)
  File "/usr/bin/autojack", line 1362, in start_slave
    dsr = get_card_rate(ldev)
  File "/usr/bin/autojack", line 1313, in get_card_rate
    adev_h.setrate(int(try_rate))
alsaaudio.ALSAAudioError: PCM device is closed
```

If I hotplug it when jack is already running :
the card appears in carla as a midi device but nothing with sound and in autojack.log a little bit different error :

```
2022-05-15 17:10:48,139 - AutoJack - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/autojack", line 1224, in msg_cb_new
    start_slave(subname)
  File "/usr/bin/autojack", line 1362, in start_slave
    dsr = get_card_rate(ldev)
  File "/usr/bin/autojack", line 1313, in get_card_rate
    adev_h.setrate(int(try_rate))
alsaaudio.ALSAAudioError: PCM device is closed
```

when I try "jack master settings" to choose the card as USB master : no sound, excepted motorboating

the card works fine with QJackCtl. (even after i had errors with studio controls)

I've tried UbStudio 21.10, 22.04 (live sessions and installed versions), same problem
I've re-installed Ubstu 20.04 in dualboot : it works !

I ve tried others sound cards :

```
2 [CODEC          ]: USB-Audio - USB AUDIO  CODEC
                      BurrBrown from Texas Instruments USB AUDIO  CODEC at usb-0000:00:14.0-3, full s
3 [DUOCAPTURE     ]: USB-Audio - DUO-CAPTURE
                      Roland DUO-CAPTURE at usb-0000:00:14.0-1, full speed
```
no problems

It seems like issue#78 but I have v 2.3.1 
updated to 2.3.2, same problem

**Comment by RavenRandomz** [comment]
It has to do with KDE. I installed ubuntu studio, installed gnome (where it would still do the audio devices), but then whenever I removed all of the kde packages, the usb configuration wouldn't work. (sudio apt remove *kde*)

Reinstalling KDE will not work. I'm going to reinstall the whole ubuntu studio :(

Update: June 06
I have reinstalled Ubuntu studio and it now is completely broken.

It can could see another interface but not my beringer.

For those who still have it broken:
You can still use the pulse_bridge which is useful if you want to hear the mixing tutorials through the monitor speakers.

BUT if you want multiple devices: https://www.youtube.com/watch?v=cgVYDM8AXWk
cat /proc/asound/cards to get the interface number
alsa_in -d hw:#
then open another terminal
alsa_out -d hw:#

The -d is important. alsa_in and alsa_out will not accept the device without the -d (device specifier).

**Comment by benjaminbanana** [comment]
done today : install ubuntustudio 22.04 (native KDE) , install backport PPA, update studiocontrol to 2.3.2
it does not works.

**Comment by ovenwerks** [comment]
I am not sure why this doesn't work but have removed that section of code. Version 2.3.4 should be out shortly.

**Comment by benjaminbanana** [comment]
udated to 2.3.4
switched "logging level to "debug"
still jams on "adding bridges"  but the error in  autojack.log is different :
```
2022-06-13 17:45:01,929 - AutoJack - DEBUG - Kill old Procs: 
2022-06-13 17:45:01,941 - AutoJack - DEBUG - JACK is False restart pulse: /org/freedesktop/systemd1/job/455
2022-06-13 17:45:01,948 - AutoJack - DEBUG - jack client closed and cleaned up
2022-06-13 17:45:17,481 - AutoJack - DEBUG - got signal - args: start
2022-06-13 17:45:17,482 - AutoJack - INFO - Got start signal.
2022-06-13 17:45:17,482 - AutoJack - INFO - Running: config_start()
2022-06-13 17:45:18,203 - AutoJack - DEBUG - phone port set to: PCH,0,0-out:playback_1
2022-06-13 17:45:20,206 - AutoJack - DEBUG - Running: config_start jack stat
2022-06-13 17:45:20,206 - AutoJack - INFO - Running: config_start after jack_stat
2022-06-13 17:45:20,213 - AutoJack - DEBUG - Pulseaudio: Impossible de décharger le module : module module-jack-source non chargé
2022-06-13 17:45:21,219 - AutoJack - DEBUG - Pulseaudio: Impossible de décharger le module : module module-jack-sink non chargé
2022-06-13 17:45:24,231 - AutoJack - DEBUG - Kill old Procs: 
2022-06-13 17:45:24,240 - AutoJack - DEBUG - JACK is True restart pulse: /org/freedesktop/systemd1/job/474
2022-06-13 17:45:24,240 - AutoJack - DEBUG - JACK is True start up jack
2022-06-13 17:45:24,522 - AutoJack - DEBUG - remove jackdbus_detect: 
2022-06-13 17:45:24,523 - AutoJack - DEBUG - Found previous jack config removing
2022-06-13 17:45:24,524 - AutoJack - DEBUG - JACK driver set to: alsa
2022-06-13 17:45:24,924 - AutoJack - DEBUG - JACK device set to: PCH,0,0
2022-06-13 17:45:25,927 - AutoJack - DEBUG - JACK rate/period/nperiods set to: 48000/1024/2
2022-06-13 17:45:29,071 - AutoJack - DEBUG - JACK started
2022-06-13 17:45:32,074 - AutoJack - DEBUG - create jack client
2022-06-13 17:45:32,143 - AutoJack - DEBUG - jack client created
2022-06-13 17:45:33,213 - AutoJack - DEBUG - Pulseaudio: 24
2022-06-13 17:45:34,281 - AutoJack - DEBUG - Pulseaudio: 25
2022-06-13 17:45:35,287 - AutoJack - DEBUG - remove module-udev-detect: 
2022-06-13 17:45:36,294 - AutoJack - DEBUG - remove module-alsa-card: 
2022-06-13 17:45:37,296 - AutoJack - DEBUG - updating extra devices
2022-06-13 17:45:38,354 - AutoJack - DEBUG - checking: PCH,0,0 channel counts: 100 100 card: 0
2022-06-13 17:45:38,355 - AutoJack - DEBUG - PCH,0,0 is master, no bridge
2022-06-13 17:45:38,855 - AutoJack - DEBUG - checking: USB1,0,0 channel counts: 100 100 card: 1
2022-06-13 17:45:38,856 - AutoJack - DEBUG - Start slave: USB1,0,0
2022-06-13 17:45:39,414 - AutoJack - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/bin/autojack", line 1739, in ses_cb_command
    config_start()
  File "/usr/bin/autojack", line 819, in config_start
    extra_devices()
  File "/usr/bin/autojack", line 142, in extra_devices
    start_slave(fullname)
  File "/usr/bin/autojack", line 1364, in start_slave
    dsr = sub_db['frame']['rate']
TypeError: 'int' object is not subscriptable
2022-06-13 17:45:39,416 - AutoJack - DEBUG - Connection changed
2022-06-13 17:45:39,416 - AutoJack - DEBUG - moving connections from system:playback_1 to system:playback_1
2022-06-13 17:45:39,416 - AutoJack - DEBUG - both ports are the same, no move done

```

**Comment by ovenwerks** [comment]
File "/usr/bin/autojack", line 1364, in start_slave
    dsr = sub_db['frame']['rate']
TypeError: 'int' object is not subscriptable
This typo has been fixed in 2.3.5 released 3 days ago

**Comment by benjaminbanana** [comment]
on XUbuntu 22.04, updated Studiocontrol to 2.3.5
jack runs, the sound card appears in Carla
but there is a sound problem : the level is very high, even with zeroing the input levels of the card.
the (background) noise is amplified, distorded to the max...  
i connected the card to meterbridge in carla --> vumeters in the red. 
the card is still unusable but still works fine with qjackctl

**Comment by eeickmeyer** [comment]
That's likely unrelated to studio-controls (it uses the same mechanism to start jack as qjackctl). Check your input in alsamixer or qasmixer.

**Comment by benjaminbanana** [comment]
i can't change anything...
 "This sound device does not have any controls" in alsamixer

**Comment by benjaminbanana** [comment]
must be the same as #83

**Comment by ovenwerks** [comment]
As the original problem seems fixed this has been closed
