### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '2.0'

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#9]
I'm getting this error on trying to start the GUI atm;

```
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1237, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 394, in __init__
    self.refresh_pulse_tab(self.i_in, self.i_out)
  File "/usr/bin/studio-controls", line 981, in refresh_pulse_tab
    self.pj_out_count.set_value(int(self.p_out_cnt[i_out]))
ValueError: invalid literal for int() with base 10: '2.0'
```

**Comment by ovenwerks** [comment]
Yup, I noticed this too, should now be fixed.

**Comment by mxmilkiib** [comment]
I'm still getting this with the latest commit.

```
  File "/usr/bin/studio-controls", line 1265, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 394, in __init__
    self.refresh_pulse_tab(self.i_in, self.i_out)
  File "/usr/bin/studio-controls", line 984, in refresh_pulse_tab
    self.pj_out_count.set_value(int(self.p_out_cnt[i_out]))
ValueError: invalid literal for int() with base 10: '2.0'
```

**Comment by ovenwerks** [comment]
@mxmilkiib: you will likely need to remove or hand edit ~/.config/autojack/autojackrc lines with:
pj-in-count = 2
pj-out-count = 2
May have 2.0 rather than the correct int 2. Also just changing these values in the GUI to 3 apply and then back to 2 and apply should fix this as well.

**Comment by mxmilkiib** [comment]
Aha, yes, there was `pj-out-count = 2.0`, making that end just `2` and the GUI opens, thanks :)
